language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
cache: pip
before_install:
  - sudo apt-get install -y pdfgrep
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install pycodestyle
script:
  - PYTHONIOENCODING=UTF-8 ./test/tsht
  - pycodestyle hocr-* setup.py
